In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [3]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

## Q1. Pandas version

In [4]:
pd.__version__

'3.0.6'

## Q2. Records count

In [5]:
df.shape

(10000, 11)

## Q3. Fuel types

In [8]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

## Q4. Missing values

In [9]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency

In [58]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(41.2)

## Q6. Median value of horsepower

In [22]:
# 1. Find the median value of the `horsepower` column in the dataset.
df.horsepower.median()

np.float64(254.0)

In [27]:
# 2. Next, calculate the most frequent value of the same `horsepower` column. == 252
most_frequent = df.horsepower.mode()[0]
most_frequent

np.float64(252.0)

In [28]:
# 3. Use the `fillna` method to fill the missing values in the `horsepower` column with the most frequent value from the previous step.
df['horsepower'] = df['horsepower'].fillna(most_frequent)

In [30]:
# 4. Now, calculate the median value of `horsepower` once again.
df.horsepower.median()

np.float64(252.0)

## Q7. Sum of weights

In [48]:
# 1. Select all the cars from Asia
asia = df[df['origin'] == 'Asia']

In [ ]:
# 2. Select only columns `vehicle_weight` and `model_year`
selected_column = asia.filter(['vehicle_weight', 'model_year'])
selected_column

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [50]:
# 3. Select the first 7 values
selected_7_values = selected_column.head(7)
selected_7_values

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [ ]:
# 4. Get the underlying NumPy array. Let's call it `X`.
X = np.array(selected_7_values)

In [64]:
# 5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
XT = X.T
XTX = np.dot(X, XT)

In [62]:
# 6. Invert `XTX`.
invert_XTX = np.linalg.pinv(XTX)

In [54]:
# 7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [ ]:
# 8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
w = np.dot(np.dot(XT, invert_XTX), y)

In [65]:
# 9. What's the sum of all the elements of the result?
w.sum()

np.float64(0.3691969690492639)